apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
images:
  - name: cognivita-frontend
    newName: docker.io/borhen2/cognivita-frontend
    newTag: e4321a9
